### ISSUE TITLE
Todo for next update

### ISSUE THREAD

**Issue by v-adhithyan** [v-adhithyan/suprabhatham-android-app#1]
- [x] Change splash screen pic with app icon
- [ ] Push notification for new updates
- [x] Multiple alarms
- [ ] Display lyrics along with playback
- [x] Revamp UI
- [x] Track installations and uninstallations
- [x] Time spent per activity
- [ ] reduce app size by compressing song and decompress after install
- [x] refactor code - it's very horrible to debug
- [x]  seek bar

**Comment by v-adhithyan** [comment]
changed splash screen image

**Comment by v-adhithyan** [comment]
tracker added
